blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/barsukon/electronic-circuit-simulator/discussions
    about: Visit our GitHub Discussions page to suggest an idea to make ECS better.
